"""initial schema

Revision ID: 9b83127c60f8
Revises: 
Create Date: 2026-07-23 10:05:58.444742
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '9b83127c60f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index('ix_audit_org_time', ['org_id', 'created_at'], unique=False)

    op.create_table('job_stats',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('connector_id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('query', sa.String(length=100), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('from_cache', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_stats_connector_id'), ['connector_id'], unique=False)
        batch_op.create_index('ix_jobstats_connector_time', ['connector_id', 'created_at'], unique=False)

    op.create_table('organisations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('connectors',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'revoked', name='connectorstatus', native_enum=False, length=20), nullable=False),
    sa.Column('connector_version', sa.String(length=50), nullable=True),
    sa.Column('hostname', sa.String(length=200), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_tally_online', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connectors_org_id'), ['org_id'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.Enum('viewer', 'accountant', 'owner', name='role', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'org_id', name='uq_membership_user_org')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=32), nullable=False),
    sa.Column('device_name', sa.String(length=200), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('companies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('connector_id', sa.String(length=32), nullable=False),
    sa.Column('tally_name', sa.String(length=300), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=True),
    sa.Column('guid', sa.String(length=100), nullable=True),
    sa.Column('financial_year_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('base_currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connector_id', 'tally_name', name='uq_company_connector_name')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_connector_id'), ['connector_id'], unique=False)
        batch_op.create_index('ix_companies_org_active', ['org_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_org_id'), ['org_id'], unique=False)

    op.create_table('snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('dataset', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('params_key', sa.String(length=64), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'dataset', 'params_key', name='uq_snapshot_company_dataset_params')
    )
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snapshots_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_snapshots_refresh_scan', ['is_stale', 'refreshed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshots_refresh_scan')
        batch_op.drop_index(batch_op.f('ix_snapshots_company_id'))

    op.drop_table('snapshots')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_org_id'))
        batch_op.drop_index('ix_companies_org_active')
        batch_op.drop_index(batch_op.f('ix_companies_connector_id'))

    op.drop_table('companies')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_family_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_org_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('connectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connectors_org_id'))

    op.drop_table('connectors')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('organisations')
    with op.batch_alter_table('job_stats', schema=None) as batch_op:
        batch_op.drop_index('ix_jobstats_connector_time')
        batch_op.drop_index(batch_op.f('ix_job_stats_connector_id'))

    op.drop_table('job_stats')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_org_time')
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
